dependencies:
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.9.0
  tr:
    url: github.com/toitlang/pkg-tr
    version: ^1.0.0
